name: CI Practice

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, CI/CD!"

      - name: Run failing test
        run: |
          echo "2 + 2 = $((2 + 2))"
          if [ $((2 + 2)) -ne 5 ]; then
            echo "Test failed!"
            exit 1
          fi
